const mobileMenuButton=document.querySelector('.mobile-menu-button');
const mainNavigation=document.querySelector('.main-navigation');
if(mobileMenuButton&&mainNavigation){mobileMenuButton.addEventListener('click',()=>{const open=mainNavigation.classList.toggle('open');mobileMenuButton.setAttribute('aria-expanded',String(open));});mainNavigation.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mainNavigation.classList.remove('open');mobileMenuButton.setAttribute('aria-expanded','false');}));window.addEventListener('resize',()=>{if(window.innerWidth>900){mainNavigation.classList.remove('open');mobileMenuButton.setAttribute('aria-expanded','false');}});}

document.querySelectorAll('a').forEach(link=>{const text=link.textContent.trim().replace(/\s+/g,' ').toLowerCase();if(text==='request a quote'){link.href='contact.html';link.removeAttribute('download');}if(text==='download profile'||text==='download corporate profile'){link.href='documents/Eloquent%20Global%20Portfolio.pdf.pdf';link.setAttribute('download','Eloquent Global Portfolio.pdf');}});

const imageFixes={'images/portfolio/feedback-management.jpg':'images/portfolio/feedback-management.png','images/portfolio/transiti.jpg':'images/portfolio/transiti.png','images/portfolio/community-platform.jpg':'images/portfolio/community-platform.png','images/marketing/digital-marketing.jpg':'images/marketing/digital-marketing.png','images/marketing/video-production.jpg':'images/marketing/video-production.png','images/marketing/commercial-photography.jpg':'images/marketing/commercial-photography.png'};
document.querySelectorAll('img').forEach((img,i)=>{const src=img.getAttribute('src');if(src&&imageFixes[src])img.src=imageFixes[src];if(i>0&&!img.hasAttribute('loading'))img.loading='lazy';if(!img.hasAttribute('decoding'))img.decoding='async';});

const siteUrl='https://eloquentglobal.com';
const socialImage=`${siteUrl}/images/logo/logo.png`;
const currentFile=window.location.pathname.split('/').pop()||'index.html';
const commercialPages=['custom-software-development.html','mvp-development.html','saas-development.html','ai-development.html'];

const supportStyle=document.createElement('style');supportStyle.textContent=`.eg-proof-strip{background:#0b1628;color:#fff;border-top:1px solid rgba(255,255,255,.08);border-bottom:1px solid rgba(255,255,255,.08)}.eg-proof-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:rgba(255,255,255,.1)}.eg-proof-item{background:#0b1628;padding:26px 24px;text-align:center}.eg-proof-item strong{display:block;font-size:clamp(1.7rem,3vw,2.4rem);line-height:1;margin-bottom:8px}.eg-proof-item span{font-size:.84rem;letter-spacing:.05em;text-transform:uppercase;opacity:.78}.eg-related-links,.eg-work-proof{padding:72px 0}.eg-related-links{background:#f6f8fa;border-top:1px solid #e5e9ee;border-bottom:1px solid #e5e9ee}.eg-related-grid,.eg-work-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:28px}.eg-related-card,.eg-work-card{display:block;padding:26px;border:1px solid #dfe5ea;background:#fff;color:inherit;text-decoration:none;transition:.2s ease}.eg-related-card:hover,.eg-work-card:hover{transform:translateY(-3px);border-color:#2f8f67}.eg-related-card h3,.eg-work-card h3{margin:0 0 10px}.eg-related-card p,.eg-work-card p{margin:0}.eg-work-card span{display:inline-block;margin-bottom:12px;font-size:.75rem;letter-spacing:.08em;text-transform:uppercase;color:#2f8f67;font-weight:700}.eg-section-head{max-width:760px}.eg-section-head h2{margin:8px 0 12px}.eg-section-cta{margin-top:26px}@media(max-width:900px){.eg-related-grid,.eg-work-grid{grid-template-columns:1fr}}@media(max-width:820px){.eg-proof-grid{grid-template-columns:1fr}}`;document.head.appendChild(supportStyle);

function insertAfter(ref,node){if(ref&&ref.parentNode)ref.parentNode.insertBefore(node,ref.nextSibling);}
function proofMarkup(home=false){return home?`<div class="container eg-proof-grid"><div class="eg-proof-item"><strong>30+</strong><span>Software Development Projects</span></div><div class="eg-proof-item"><strong>50+</strong><span>Marketing Projects</span></div><div class="eg-proof-item"><strong>2019</strong><span>Established</span></div></div>`:`<div class="container eg-proof-grid"><div class="eg-proof-item"><strong>30+</strong><span>Software Development Projects</span></div><div class="eg-proof-item"><strong>USA · UK · Europe</strong><span>Remote International Delivery</span></div><div class="eg-proof-item"><strong>2019</strong><span>Established</span></div></div>`;}

if(currentFile==='index.html'){const actions=document.querySelector('.hero-actions');if(actions&&!actions.querySelector('a[href="custom-software-development.html"]')){const a=document.createElement('a');a.href='custom-software-development.html';a.className='button button-secondary';a.textContent='Custom Software Development';actions.appendChild(a);}const hero=document.querySelector('.hero-section');if(hero&&!document.querySelector('.eg-proof-strip')){const s=document.createElement('section');s.className='eg-proof-strip';s.innerHTML=proofMarkup(true);insertAfter(hero,s);}}

if(currentFile==='services.html'){
 const actions=document.querySelector('.services-hero-actions');if(actions&&!actions.querySelector('a[href="custom-software-development.html"]')){const a=document.createElement('a');a.href='custom-software-development.html';a.className='button button-secondary';a.textContent='Custom Software Development';actions.appendChild(a);}
 const hero=document.querySelector('.services-hero-section');if(hero&&!document.querySelector('.eg-proof-strip')){const s=document.createElement('section');s.className='eg-proof-strip';s.innerHTML=proofMarkup(true);insertAfter(hero,s);}
 const software=[...document.querySelectorAll('.service-capability h3')].find(h=>h.textContent.trim()==='Custom Software Development');if(software){const box=software.closest('.service-capability');if(box&&!box.querySelector('a[href="custom-software-development.html"]')){const a=document.createElement('a');a.href='custom-software-development.html';a.className='text-link';a.innerHTML='Explore custom software development <span>→</span>';box.appendChild(a);}}
 const aiSection=document.querySelector('#ai-automation');if(aiSection){if(!aiSection.querySelector('a[href="ai-development.html"]')){const a=document.createElement('a');a.href='ai-development.html';a.className='text-link';a.innerHTML='Explore AI development services <span>→</span>';aiSection.appendChild(a);}if(!aiSection.querySelector('a[href="ai-automation.html"]')){const a=document.createElement('a');a.href='ai-automation.html';a.className='text-link';a.innerHTML='Explore AI automation services <span>→</span>';aiSection.appendChild(a);}}
 const grid=document.querySelector('.service-overview-grid');[['07','MVP','MVP Development','Focused startup products built from idea to launch-ready first release.','mvp-development.html'],['08','SaaS','SaaS Development','Custom subscription products and SaaS applications built for continued growth.','saas-development.html'],['09','AI','AI Development','Custom AI applications, AI agents and AI-enabled product features.','ai-development.html'],['10','AUTO','AI Automation','AI-powered workflows and business process automation for repetitive operational work.','ai-automation.html']].forEach(([n,icon,title,copy,href])=>{if(grid&&!grid.querySelector(`a[href="${href}"]`)){const a=document.createElement('a');a.href=href;a.className='overview-card';a.innerHTML=`<span class="overview-number">${n}</span><div class="overview-icon">${icon}</div><h3>${title}</h3><p>${copy}</p><span class="overview-arrow">→</span>`;grid.appendChild(a);}});
}

if(commercialPages.includes(currentFile)){
 const main=document.querySelector('main'),hero=main?.querySelector('section');if(hero&&!document.querySelector('.eg-proof-strip')){const s=document.createElement('section');s.className='eg-proof-strip';s.innerHTML=proofMarkup(false);insertAfter(hero,s);}
 if(main&&!document.querySelector('.eg-work-proof')){const work=document.createElement('section');work.className='eg-work-proof';work.innerHTML=`<div class="container"><div class="eg-section-head"><p class="section-eyebrow">Selected Software Work</p><h2>Experience across 30+ software development projects.</h2><p>Our software portfolio includes web platforms, mobile applications, enterprise systems and connected digital products.</p></div><div class="eg-work-grid"><a class="eg-work-card" href="portfolio.html"><span>Enterprise Software</span><h3>Feedback Management System</h3><p>A web and mobile platform supporting customer feedback and real-time reporting.</p></a><a class="eg-work-card" href="portfolio.html"><span>Mobile Application</span><h3>Transiti Rideshare</h3><p>A mobile carpooling platform featuring vehicle matching, location services and digital payments.</p></a><a class="eg-work-card" href="portfolio.html"><span>Web & Mobile Platform</span><h3>Community Platform</h3><p>A connected community platform supporting news, events, member interaction and digital services.</p></a></div><div class="eg-section-cta"><a href="portfolio.html" class="button button-secondary">View Our Software Work</a></div></div>`;const faq=main.querySelector('#faq,.mvp-faq-section,.csd-faq-section,.saas-faq-section,.ai-faq-section');faq?main.insertBefore(work,faq):main.appendChild(work);}
 if(main&&!document.querySelector('.eg-related-links')){const maps={
  'custom-software-development.html':[['MVP Development','Validate a new product with focused version-one scope.','mvp-development.html'],['SaaS Development','Build subscription software and SaaS products.','saas-development.html'],['AI Development','Build AI-powered applications and product capabilities.','ai-development.html']],
  'mvp-development.html':[['Custom Software Development','Build systems around specific operational requirements.','custom-software-development.html'],['SaaS Development','Move from a SaaS MVP into a fuller subscription product.','saas-development.html'],['AI Development','Build and validate AI-enabled product features.','ai-development.html']],
  'saas-development.html':[['MVP Development','Start a SaaS concept with a focused MVP.','mvp-development.html'],['Custom Software Development','Build custom business platforms and integrations.','custom-software-development.html'],['AI Development','Integrate AI agents and AI product features.','ai-development.html']],
  'ai-development.html':[['AI Automation','Automate repetitive business processes and connected workflows with AI.','ai-automation.html'],['Custom Software Development','Build wider business applications and platforms.','custom-software-development.html'],['SaaS Development','Build AI-enabled SaaS products and subscription platforms.','saas-development.html']]
 };const links=maps[currentFile];const sec=document.createElement('section');sec.className='eg-related-links';sec.innerHTML=`<div class="container"><div class="eg-section-head"><p class="section-eyebrow">Related Development Services</p><h2>Choose the path that fits the product and business objective.</h2></div><div class="eg-related-grid">${links.map(([t,c,h])=>`<a class="eg-related-card" href="${h}"><h3>${t}</h3><p>${c}</p></a>`).join('')}</div></div>`;const faq=main.querySelector('#faq,.mvp-faq-section,.csd-faq-section,.saas-faq-section,.ai-faq-section');faq?main.insertBefore(sec,faq):main.appendChild(sec);}
}

if(currentFile==='portfolio.html'){const first=document.querySelector('main')?.querySelector('section');if(first&&!document.querySelector('.eg-proof-strip')){const s=document.createElement('section');s.className='eg-proof-strip';s.innerHTML=proofMarkup(true);insertAfter(first,s);}}

const seoPages={
 'index.html':['Software Development & Digital Marketing Company | Eloquent Global','Eloquent Global delivers custom software, web, mobile, AI, cloud and digital marketing solutions, backed by 30+ software development projects and 50+ marketing projects.',`${siteUrl}/`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'about.html':['About Eloquent Global | Software & Digital Solutions Company','Learn about Eloquent Global Pvt Ltd, a Sri Lankan software engineering and digital marketing company established in 2019 and serving international clients through remote delivery.',`${siteUrl}/about.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'services.html':['Software, MVP, SaaS & AI Services | Eloquent Global','Explore Eloquent Global services including custom software, MVP development, SaaS development, AI development, AI automation, web, mobile, cloud and digital marketing.',`${siteUrl}/services.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'custom-software-development.html':['Custom Software Development Company | Eloquent Global','Custom software development for businesses in the USA, UK and Europe, backed by experience across 30+ software development projects.',`${siteUrl}/custom-software-development.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'mvp-development.html':['MVP Development Services for Startups | Eloquent Global','MVP development services for startups in the USA, UK and Europe, from product planning and UX/UI through engineering, testing, launch and iteration.',`${siteUrl}/mvp-development.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'saas-development.html':['SaaS Development Company | Eloquent Global','SaaS development services for startups and businesses in the USA, UK and Europe, covering product planning, UX/UI, engineering, integrations and post-launch development.',`${siteUrl}/saas-development.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'ai-development.html':['AI Development Company | Eloquent Global','AI development services for businesses and startups in the USA, UK and Europe, including custom AI applications, AI agents and AI-enabled software products.',`${siteUrl}/ai-development.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'ai-automation.html':['AI Automation Services | Eloquent Global','AI automation services for businesses in the USA, UK and Europe, including AI-powered workflows, intelligent assistants, document processing and connected business automation.',`${siteUrl}/ai-automation.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'portfolio.html':['Software & Digital Marketing Portfolio | Eloquent Global','Explore selected Eloquent Global work from experience across 30+ software development projects and 50+ marketing projects.',`${siteUrl}/portfolio.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'leadership.html':['Leadership Team | Eloquent Global Pvt Ltd','Meet the leadership team guiding Eloquent Global across software engineering, operations, business strategy, creative services and digital marketing.',`${siteUrl}/leadership.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'contact.html':['Contact Eloquent Global | Software & Digital Services','Contact Eloquent Global to discuss custom software, MVP, SaaS, AI development, AI automation, web, mobile, digital marketing or an international partnership.',`${siteUrl}/contact.html`,'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'],
 'requestquote.html':['Request a Quote | Eloquent Global Pvt Ltd','Contact Eloquent Global to discuss a software development or digital marketing requirement.',`${siteUrl}/contact.html`,'noindex,follow']
};
const [title,description,canonical,robots]=seoPages[currentFile]||seoPages['index.html'];document.title=title;
function meta(selector,key,value){let el=document.head.querySelector(selector);if(!el){el=document.createElement('meta');const m=selector.match(/meta\[(name|property)="([^"]+)"\]/);if(m)el.setAttribute(m[1],m[2]);document.head.appendChild(el);}el.setAttribute(key,value);}
function link(rel,href){let el=document.head.querySelector(`link[rel="${rel}"]`);if(!el){el=document.createElement('link');el.rel=rel;document.head.appendChild(el);}el.href=href;}
meta('meta[name="description"]','content',description);meta('meta[name="robots"]','content',robots);meta('meta[name="googlebot"]','content',robots);meta('meta[property="og:title"]','content',title);meta('meta[property="og:description"]','content',description);meta('meta[property="og:type"]','content','website');meta('meta[property="og:url"]','content',canonical);meta('meta[property="og:site_name"]','content','Eloquent Global Pvt Ltd');meta('meta[property="og:image"]','content',socialImage);meta('meta[property="og:image:alt"]','content','Eloquent Global Pvt Ltd');meta('meta[name="twitter:card"]','content','summary_large_image');meta('meta[name="twitter:title"]','content',title);meta('meta[name="twitter:description"]','content',description);meta('meta[name="twitter:image"]','content',socialImage);meta('meta[name="theme-color"]','content','#0b1628');link('canonical',canonical);link('icon',`${siteUrl}/images/logo/logo.png`);link('apple-touch-icon',`${siteUrl}/images/logo/logo.png`);

if(!document.head.querySelector('script[type="application/ld+json"]')){const org={'@context':'https://schema.org','@type':'Organization','@id':`${siteUrl}/#organization`,name:'Eloquent Global Pvt Ltd',url:`${siteUrl}/`,logo:`${siteUrl}/images/logo/logo.png`,foundingDate:'2019',email:'mailto:jayamaha007@gmail.com',telephone:'+94 76 370 1223',address:{'@type':'PostalAddress',addressLocality:'Moratuwa',addressCountry:'LK'}};const website={'@context':'https://schema.org','@type':'WebSite','@id':`${siteUrl}/#website`,url:`${siteUrl}/`,name:'Eloquent Global',publisher:{'@id':`${siteUrl}/#organization`}};const page={'@context':'https://schema.org','@type':currentFile==='contact.html'?'ContactPage':currentFile==='portfolio.html'?'CollectionPage':(currentFile==='about.html'||currentFile==='leadership.html')?'AboutPage':'WebPage','@id':`${canonical}#webpage`,url:canonical,name:title,description,isPartOf:{'@id':`${siteUrl}/#website`},about:{'@id':`${siteUrl}/#organization`}};const data=[org,website,page];if(currentFile==='services.html'){const services=[['Custom Software Development','custom-software-development.html'],['MVP Development','mvp-development.html'],['SaaS Development','saas-development.html'],['AI Development','ai-development.html'],['AI Automation','ai-automation.html']];data.push({'@context':'https://schema.org','@type':'ItemList',name:'Eloquent Global Services',itemListElement:services.map((s,i)=>({'@type':'ListItem',position:i+1,item:{'@type':'Service',name:s[0],url:`${siteUrl}/${s[1]}`,provider:{'@id':`${siteUrl}/#organization`}}}))});}if(currentFile!=='index.html'&&currentFile!=='requestquote.html'){data.push({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:`${siteUrl}/`},{'@type':'ListItem',position:2,name:currentFile==='services.html'?'Services':currentFile==='portfolio.html'?'Our Work':currentFile==='contact.html'?'Contact':'Page',item:canonical}]});}const s=document.createElement('script');s.type='application/ld+json';s.textContent=JSON.stringify(data);document.head.appendChild(s);}
